# Generated by Django 4.2.7 on 2023-11-07 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intercambio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Opciones",
            new_name="Opcion",
        ),
    ]
