# Generated by Django 4.2.7 on 2023-11-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("intercambio", "0002_rename_opciones_opcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="año",
        ),
        migrations.AddField(
            model_name="evento",
            name="anio",
            field=models.IntegerField(
                choices=[(2022, 2022), (2023, 2023)], default=2023
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="santa",
            name="destinatario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="santa_destinatario",
                to="intercambio.santa",
            ),
        ),
        migrations.AddField(
            model_name="santa",
            name="excepcion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="santa_excepcion_obsequio",
                to="intercambio.santa",
            ),
        ),
        migrations.AddField(
            model_name="santa",
            name="organizador",
            field=models.BooleanField(default=False),
        ),
    ]
