# Generated by Django 4.2.7 on 2023-11-08 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "intercambio",
            "0004_evento_fecha_ultimo_sorteo_evento_sorteo_realizado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="santa",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
