# Generated by Django 4.2.7 on 2023-11-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("intercambio", "0005_alter_santa_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcion",
            name="evento",
        ),
        migrations.RemoveField(
            model_name="santa",
            name="eventos",
        ),
        migrations.CreateModel(
            name="Participacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intercambio.evento",
                    ),
                ),
                (
                    "santa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intercambio.santa",
                    ),
                ),
            ],
            options={
                "unique_together": {("santa", "evento")},
            },
        ),
    ]
