# Generated by Django 4.2.7 on 2023-11-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("intercambio", "0007_opcion_evento_alter_santa_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcion",
            name="evento",
        ),
        migrations.RemoveField(
            model_name="opcion",
            name="santa",
        ),
        migrations.AddField(
            model_name="opcion",
            name="paricipacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="intercambio.participacion",
            ),
            preserve_default=False,
        ),
    ]
